secrets:
    GEMINI_API_KEY: ENC[AES256_GCM,data:BGe8vhho/BEuOQoUUt9QzcXAzQ==,iv:q4H4uVq2Gna+RJ8TGC1RBODYC+Ge9OZrZhDC469G4Ao=,tag:c8m5FkZ95idrE+ehP3qB/w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:ka4CWRt7hg69Dz7/eXedYaGSRQ==,iv:YQND+aE8XjRsIHB0q/Zen5rH69sQ2u6I4JBaH9ejDcc=,tag:CcnFwTydsJ0f1JC8HerTug==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:tsBBHkmyoxo5DcfPx34O3PV3UmdwBQ==,iv:NxsnvUfStt0Pa/hyX/OjifbwPLKGb3iSe76Vljf1sYI=,tag:7VZYDxYmInKPdwzSgouOEQ==,type:str]
    ZHIPU_API_KEY: ENC[AES256_GCM,data:sbCpZmclDJ67DY8MfMuX3P1A,iv:OoowGp2x19vI6bn4UFNNG2tmRRuK4q1PReIfprEqjO4=,tag:734Xqu1DaE6o16uVewGxpw==,type:str]
    MCP_SECRETS_VERSION: ENC[AES256_GCM,data:3w==,iv:uAIOaPMSbKKxXedVeiC6MLKDsBfLh+him8r3Pj2joqg=,tag:GEfQDnZJ6RkQ/fV6rWYTXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rxakdpyzucls2kahxrdtd2uy2sv9vt0wjwfsm4j80mq8a357h3eqpav98j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbEY5ZUdnVGY1RWJRVEVM
            Z0RUeHZlR2NsUDUvTTBsR2hlU010VnJITndNCjA3bjVvN1U2cEk0VGNZcWNkWWU4
            VDFBL3FtZTJ3c21jZjZ1RE5NcVBlcG8KLS0tIHFhNnIyamIrZW1semlKVHo0em13
            SzgwL1k4dmVtQnEyQ1o4TDVwQzlPWnMKhyz1oOG+s3yozYZzuhk4e8QzmuK2pg5S
            xFzb/Kl4aJ3xlt4PfcQetgnopm+5g8i8O3BFo53rFaxcmg86qY4lSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T22:44:57Z"
    mac: ENC[AES256_GCM,data:ORfCbJk2pLo7IhH7nxWXCK7Ydvkmx7VMO/hH/7V+jtaW4qEbAHUTjMZL5pbaIZLZij2BIGfdX1bbAGAVOEsXeT8ZGjayA29zWjmezUsItnW9MJ6Bq/l9sJLeIv8DPcb9xJqnoIycw8rTshk7ZgI06IpshD5kLf5U39TQ8eKVCWI=,iv:E6RoYuEwPTSHMtbTXud4oati7GEmM1Qq9F9zsk0w6DU=,tag:ZHCs1uceKs95sOVyBSwX4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.8.1
