import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBars,
  faBell,
  faCircleHalfStroke,
  faDiagramProject,
  faGaugeHigh,
  faKey,
  faMessage,
  faMoon,
  faRobot,
  faSatelliteDish,
  faServer,
  faShieldHalved,
  faShuffle,
  faStore,
  faSun,
  faTableColumns,
  faUsersGear,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faBars,
  faBell,
  faCircleHalfStroke,
  faDiagramProject,
  faGaugeHigh,
  faKey,
  faMoon,
  faMessage,
  faRobot,
  faSatelliteDish,
  faServer,
  faShieldHalved,
  faShuffle,
  faStore,
  faSun,
  faTableColumns,
  faUsersGear,
);
