name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            server/pyproject.toml
            agents-hub/pyproject.toml

      - name: Install dependencies via Makefile
        run: make install

      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      AGENTS_ROOT: agents-hub/app/agents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            server/pyproject.toml
            agents-hub/pyproject.toml

      - name: Install dependencies via Makefile
        run: make install

      - name: Run test suite
        id: run-tests
        run: |
          set -o pipefail
          make test 2>&1 | tee pytest.log

      - name: Upload pytest log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: pytest.log
          if-no-files-found: ignore

  smoke:
    runs-on: ubuntu-latest
    env:
      AGENTS_ROOT: agents-hub/app/agents
      SMOKE_HOST: 127.0.0.1
      SMOKE_PORT: '8000'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            server/pyproject.toml
            agents-hub/pyproject.toml

      - name: Install dependencies via Makefile
        run: make install

      - name: Run smoke tests
        id: run-smoke
        run: |
          set -o pipefail
          make smoke 2>&1 | tee uvicorn.log

      - name: Upload uvicorn log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: uvicorn-log
          path: uvicorn.log
          if-no-files-found: ignore
