name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Enable Corepack (pnpm)
        run: corepack enable
      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Vitest suite
        run: pnpm --dir app test -- --reporter=dot

  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Pytest suite
        run: pytest

  diagnostics:
    name: DX diagnostics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable Corepack (pnpm)
        run: corepack enable
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install toolchain via Makefile
        run: make install
      - name: Run make doctor
        run: make doctor
